### ISSUE TITLE
Problem with latest Airflow image: ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by alexlopespereira** [bitnami/bitnami-docker-airflow#139]
### Name and Version

2.3.1-debian-10-r0 and latest

### What steps will reproduce the bug?

1. I followed the exact steps from 1 to 4 as explained in the README of this repo. Created the network, volumes, then run redis, postgresql and airflow containers. I'm using Ubuntu 22.04.

### What is the expected behavior?

The container was supposed to run without error. The webserver inside the container does not run correctly.
Instead, the webserver shows the following error message in the browser:

```
    self.dialect.do_execute(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "session" does not exist
LINE 2: FROM session 
             ^

[SQL: SELECT session.id AS session_id_1, session.session_id AS session_session_id, session.data AS session_data, session.expiry AS session_expiry 
FROM session 
WHERE session.session_id = %(session_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'session_id_1': '9050d9a0-4e0a-4d73-9b60-1f959be79fa6', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

### What do you see instead?

2. The following error message apperas in the airflow container logs:

```
[2022-06-03 23:44:20,604] {providers_manager.py:215} INFO - Optional provider feature disabled when importing 'airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook' from 'apache-airflow-providers-google' package
[2022-06-03 23:44:20,612] {providers_manager.py:223} WARNING - Exception when importing 'airflow.providers.microsoft.mssql.hooks.mssql.MsSqlHook' from 'apache-airflow-providers-microsoft-mssql' package
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers_manager.py", line 255, in _sanity_check
    imported_class = import_string(class_name)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/module_loading.py", line 32, in import_string
    module = import_module(module_path)
  File "/opt/bitnami/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 21, in <module>
    import pymssql
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/pymssql/__init__.py", line 3, in <module>
    from ._pymssql import *

ImportError: /opt/bitnami/airflow/venv/lib/python3.8/site-packages/pymssql/_pymssql.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

### Additional information

I tried to build the image myself with the latest Dockerfile, the same message appears. This same error repeats when I use the docker-compose and when I run on other linux distributions.

**Comment by barajas123** [comment]
any updates on this ?

**Comment by prinzpiuz** [comment]
same issue here

**Comment by gongomgra** [comment]
We filed an internal task for our engineering team to work on it, but unfortunately we can't provide you with any ETA on this. This will be worked on by the team on a priority and availability basis. We will notify you in this thread as soon as the fixed image is published. Thanks for your patience

**Comment by gongomgra** [comment]
Hi @alexlopespereira, @prinzpiuz, 

We released a new image of the Airflow container, tagged as `2.3.2-debian-11-r8`, fixing this error. We found out that it was caused because the `pymssql` binaries are shrinked as part of our build process in order to reduce the container size. Disabling this process for the package solves the issue. Please confirm your issue get solved after updating the airflow image.

**Comment by alexlopespereira** [comment]
> Hi @alexlopespereira, @prinzpiuz,
> 
> We released a new image of the Airflow container, tagged as `2.3.2-debian-11-r8`, fixing this error. We found out that it was caused because the `pymssql` binaries are shrinked as part of our build process in order to reduce the container size. Disabling this process for the package solves the issue. Please confirm your issue get solved after updating the airflow image.

It works great!

**Comment by gongomgra** [comment]
Hi @subhosuper, @alexlopespereira, thanks for letting us know. I'm glad it worked for you! I'm closing this thread as solved.
