### ISSUE TITLE
Airflow papermill operator not found

### ISSUE THREAD

**Issue by cccs-cat001** [bitnami/bitnami-docker-airflow#15]
**Description**

I'm trying to use the papermill operator for airflow. Airflow complains that there is no module for PapermillOperator. It appears that airflow doesn't come installed with all the operators, which is fine. So I exec into the container and `pip install apache-airflow[papermill]` but it gives me an error:
```
# pip install apache-airflow[papermill]
Collecting apache-airflow[papermill]
  Using cached https://files.pythonhosted.org/packages/74/cb/3a4bcfcdb75897607c0c4d9ec17f3c3d6eb4973930d2fa59bd0b47c20a67/apache_airflow-1.10.6-py2.py3-none-any.whl
Collecting graphviz>=0.12
  Using cached https://files.pythonhosted.org/packages/94/cd/7b37f2b658995033879719e1ea4c9f171bf7a14c16b79220bd19f9eda3fe/graphviz-0.13-py2.py3-none-any.whl
Collecting json-merge-patch==0.2
  Using cached https://files.pythonhosted.org/packages/39/62/3b783faabac9a099877397d8f7a7cc862a03fbf9fb1b90d414ea7c6bb096/json-merge-patch-0.2.tar.gz
Collecting marshmallow-sqlalchemy<0.19.0,>=0.16.1
  Using cached https://files.pythonhosted.org/packages/35/b0/60b51e7e4096551d7b3ee636ce4dd5034b6889763b7ddc98dc2057b31eef/marshmallow_sqlalchemy-0.18.0-py2.py3-none-any.whl
Collecting tzlocal<2.0.0,>=1.4
  Using cached https://files.pythonhosted.org/packages/cb/89/e3687d3ed99bc882793f82634e9824e62499fdfdc4b1ae39e211c5b05017/tzlocal-1.5.1.tar.gz
Collecting psutil<6.0.0,>=4.2.0
  Using cached https://files.pythonhosted.org/packages/47/ea/d3b6d6fd0b4a6c12984df652525f394e68c8678d2b05075219144eb3a1cf/psutil-5.6.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/distributions/source/legacy.py", line 37, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/distributions/source/legacy.py", line 90, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "/opt/bitnami/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
zipimport.ZipImportError: can't decompress data; zlib not available

```
I tried installing the papermill operator on a different machine with plain airflow (not through docker image, not from bitnami) and it installed just fine. So it's something to do with the preinstalled python we presume. 

**Steps to reproduce the issue:**

1. Launch an Airflow instance in Kubernetes using the binami/airflow helm chart
2. Create a DAG using the PapermillOperator and make sure it gets put into the pod for Airflow
3. Airflow will complain that no module exists for PapermillOperator. 

**Describe the results you received:**

Had to exec into the container to install the papermill operator, received the above error. 

**Describe the results you expected:**

Ideally the expected results would have the papermill operator installed by default, but I'd also accept the papermill operator installing without issues when done through a pip install. 

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
using the bitnami/airflow helm chart to run airflow on a kubernetes cluster. This image is used for the web deployment.

**Comment by cccs-cat001** [comment]
I tried installing some other, non-Airflow packages and got the same error. This time it was trying to install the plone.staticresources package after successfully installing many other plone packages: 
```
Collecting plone.staticresources
  Downloading https://files.pythonhosted.org/packages/61/27/c9e122f8eec2f39be5ad9102c0499d50eb10aa04b525e4a716f4252587e0/plone.staticresources-1.1.0.tar.gz (39.7MB)
     |################################| 39.7MB 45kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/distributions/source/legacy.py", line 37, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_internal/distributions/source/legacy.py", line 90, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "/opt/bitnami/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
zipimport.ZipImportError: can't decompress data; zlib not available
```

**Comment by andresbono** [comment]
Hi @cccs-cat001, we would like to reproduce the issue first so we can find solutions. However, we couldn't get the same error when trying to install the operator with pip.

What is the specific version of the container that you are using? You can get that information by showing the `BITNAMI_IMAGE_VERSION` environment variable inside the container:

```
env | grep BITNAMI_IMAGE_VERSION
```

Are you just doing `kubectl exec ...` and then `pip install apache-airflow[papermill]` after installing the helm chart? Did you execute any previous commands?

Can you also point us to documentation on how to configure Apache Airflow operators?
