### ISSUE TITLE
[BUG REPORT INFORMATION] LDAP3 lib is not found

### ISSUE THREAD

**Issue by aissarmurad** [bitnami/bitnami-docker-airflow#26]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

**Steps to reproduce the issue:**

1. First Step, set up the Airflow LDAP (you can do that using Environment Variables)
```
AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
  AIRFLOW__WEBSERVER__RBAC:         "False"
  AIRFLOW__WEBSERVER__AUTH_BACKEND: "airflow.contrib.auth.backends.ldap_auth"
AIRFLOW__LDAP__URI: "ldap://your.ldap.server:389"
  AIRFLOW__LDAP__USER_FILTER: "objectClass=*"
  AIRFLOW__LDAP__USER_NAME_ATTR: "sAMAccountName"
  AIRFLOW__LDAP__GROUP_MEMBER_ATTR: "memberOf"
  AIRFLOW__LDAP__SUPERUSER_FILTER: "memberOf=CN=airflow_admins,CN=Users,DC=ldap,DC=server"
  AIRFLOW__LDAP__DATA_PROFILER_FILTER: "memberOf=CN=airflow_data_profilers,CN=Users,DC=ldap,DC=server"
  AIRFLOW__LDAP__BIND_USER: "CN=adjoin,CN=Managed Service Accounts,DC=ldap,DC=server"
  AIRFLOW__LDAP__BIND_PASSWORD: "XXXXXX"
  AIRFLOW__LDAP__BASEDN: "DC=ldap,DC=server"
  AIRFLOW__LDAP__CACERT: "/etc/ca/your-ca-certificate.crt"
  AIRFLOW__LDAP__SEARCH_SCOPE: "SUBTREE"
  AIRFLOW__LDAP__IGNORE_MALFORMED_SCHEMA: "False"
```
2. Run the services using the `docker-compose.yml`

**Describe the results you received:**

```
[2020-01-29 01:01:56,385] {__init__.py:76} CRITICAL - Cannot import authentication module airflow.contrib.auth.backends.ldap_auth. Please correct your authentication backend or disable authentication: No module named 'ldap3'
[2020-01-29 01:01:56,385] {cli_action_loggers.py:86} DEBUG - Calling callbacks: []
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/__init__.py", line 68, in load_login
    login = import_module(auth_backend)
  File "/opt/bitnami/airflow/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/contrib/auth/backends/ldap_auth.py", line 27, in <module>
    from ldap3 import Server, Connection, Tls, set_config_parameter, LEVEL, SUBTREE
ModuleNotFoundError: No module named 'ldap3'

```

**Describe the results you expected:**

I'd like to have the ldap3 package installed by default.

In the future, I'd like to install other Python packages more easily.
Maybe setting up an environment variable and doing that in runtime when the container is launching.

**Additional information you deem important (e.g. issue happens only occasionally):**

* Issue happens always

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

```
BITNAMI_APP_NAME=airflow
BITNAMI_IMAGE_VERSION=1.10.7-debian-10-r3
```

**Comment by aissarmurad** [comment]
Can I submit a PR?

**Comment by javsalgar** [comment]
Hi,

Thank you very much for reporting. Feel free to submit a PR to this repository and we will review it.
