### ISSUE TITLE
Cant load a custom DAG into 

### ISSUE THREAD

**Issue by goal86sg** [bitnami/bitnami-docker-airflow#38]
**Description**

Trying to load a custom dag to the default mount
**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

Trying to load a custom DAG file into airflow
**Describe the results you expected:**

xxx@xxx:~/Code/platformplatform/airflow$ docker exec -ti airflow_airflow_1 airflow list_dags
[2020-04-16 14:03:45,917] {__init__.py:51} INFO - Using executor CeleryExecutor
[2020-04-16 14:03:45,918] {dagbag.py:396} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags
[2020-04-16 14:03:45,962] {dagbag.py:239} ERROR - Failed to import: /opt/bitnami/airflow/dags/Helloworld.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/models/dagbag.py", line 236, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/opt/bitnami/airflow/venv/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/Helloworld.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2020-04-16 14:03:45,988] {dagbag.py:239} ERROR - Failed to import: /opt/bitnami/airflow/dags/tuto.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/models/dagbag.py", line 236, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/opt/bitnami/airflow/venv/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/tuto.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2020-04-16 14:03:46,101] {dagbag.py:239} ERROR - Failed to import: /opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/example_dags/Helloworld.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/models/dagbag.py", line 236, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/opt/bitnami/airflow/venv/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/example_dags/Helloworld.py", line 7        
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

-------------------------------------------------------------------
DAGS
-------------------------------------------------------------------
example_bash_operator
example_branch_dop_operator_v3
example_branch_operator
example_complex
example_external_task_marker_child
example_external_task_marker_parent
example_http_operator
example_nested_branch_dag
example_passing_params_via_test_command
example_pig_operator
example_python_operator
example_short_circuit_operator
example_skip_dag
example_subdag_operator
example_subdag_operator.section-1
example_subdag_operator.section-2
example_trigger_controller_dag
example_trigger_target_dag
example_xcom
latest_only
latest_only_with_trigger
test_utils
tutorial
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
on ubuntu OS

**Comment by goal86sg** [comment]
solved

**Comment by dani8art** [comment]
Ok thanks!

**Comment by rasikas** [comment]
I didn't create new issue as my case is similar to this one.
1. First documentation says we can load the custom dags into `/opt/bitnami/airflow/dags` - however in the `airflow` I can see only `/opt/bitnami/airflow/data` folder is  having a link to `/bitnami/airflow`

~~~sh
airflow@da8031ac8399:/$ ls -al /opt/bitnami/airflow/
total 76
drwxrwxr-x 1       0 airflow 4096 Apr 26 01:14 .
drwxrwxr-x 1       0 airflow 4096 Apr 25 11:15 ..
-rw-r--r-- 1 airflow airflow 6624 Apr 26 01:13 airflow.cfg
-rw-r--r-- 1 airflow airflow    3 Apr 26 01:14 airflow-webserver.pid
drwxrwxr-x 1       0 airflow 4096 Apr 25 11:15 dags
lrwxrwxrwx 1 airflow airflow   21 Apr 26 01:14 data -> /bitnami/airflow/data
drwxr-xr-x 2 airflow airflow 4096 Apr 26 01:14 extra
~~~

so we can copy dags to `/data/` folder only. (then need to bash into the docker and copy it from `data` folder to `dags` folder.

2. Having our custom dags copied to `dags` folder, I can now list the dag. Ex: I can see `ras_tutorial` which is a exact copy of existing `tutorial` dag.

~~~sh
docker exec -ti bitnami_airflow_1 airflow list_dags
[2020-04-26 01:49:17,287] {__init__.py:51} INFO - Using executor CeleryExecutor
[2020-04-26 01:49:17,301] {dagbag.py:396} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags


-------------------------------------------------------------------
DAGS
-------------------------------------------------------------------
example_bash_operator
example_branch_dop_operator_v3
example_branch_operator
example_complex
example_external_task_marker_child
example_external_task_marker_parent
example_http_operator
example_nested_branch_dag
example_passing_params_via_test_command
example_pig_operator
example_python_operator
example_short_circuit_operator
example_skip_dag
example_subdag_operator
example_subdag_operator.section-1
example_subdag_operator.section-2
example_trigger_controller_dag
example_trigger_target_dag
example_xcom
latest_only
latest_only_with_trigger
ras_simple_tute
ras_tutorial
test_utils
tutorial
~~~

But I don't see it in the Airflow UI or I cannot run it. I can run the provided `tutorial` DAG without any issue.

when running the provided `tutorial` dag
~~~sh
$ docker exec -ti bitnami_airflow_1 airflow trigger_dag tutorial
[2020-04-26 01:43:55,975] {__init__.py:51} INFO - Using executor CeleryExecutor
[2020-04-26 01:43:55,980] {dagbag.py:396} INFO - Filling up the DagBag from /opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/example_dags/tutorial.py
Created <DagRun tutorial @ 2020-04-26 01:43:56+00:00: manual__2020-04-26T01:43:56+00:00, externally triggered: True>
~~~

and when trying to trigger the custom dag
~~~sh
$ docker exec -ti bitnami_airflow_1 airflow trigger_dag ras_tutorial
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/bin/airflow", line 37, in <module>
    args.func(args)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 237, in trigger_dag
    execution_date=args.exec_date)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/api/client/local_client.py", line 34, in trigger_dag
    execution_date=execution_date)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/api/common/experimental/trigger_dag.py", line 124, in trigger_dag
    raise DagNotFound("Dag id {} not found in DagModel".format(dag_id))
airflow.exceptions.DagNotFound: Dag id ras_tutorial not found in DagModel
~~~

![image](https://user-images.githubusercontent.com/1381205/80295375-89dcca00-87b5-11ea-8df1-cef7e7bb6fe4.png)

Any guide pointing me to right direction would be a great help, Thanks

**Comment by dani8art** [comment]
Hi @goal86sg, sorry but I cannot reproduce the issue, this is what I did.

1. Create a new volume with my dag:

```diff
  airflow:
    image: bitnami/airflow:1
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    ports:
      - "8080:8080"
    volumes:
+      - ./dags:/opt/bitnami/airflow/dags/local
      - airflow_data:/bitnami
```

2. Clean the persistent volumes and restart the deployment.

```bash
$ docker-compose down -v && docker-compose up -d
```

3. Trigger my dag

```bash
$ docker-compose exec airflow airflow trigger_dag mydags
```

I've attached an example, please try it and let us know if you have any issue.

Thank you.

[airflow-G600772740.tar.gz](https://github.com/bitnami/bitnami-docker-airflow/files/4545333/airflow-G600772740.tar.gz)

**Comment by joehoeller** [comment]
@dani8art i have tried this and to no avail - any ideas?

**Comment by alvneiayu** [comment]
hi @joehoeller 

I saw that you opened a new [issue](https://github.com/bitnami/bitnami-docker-airflow/issues/88). We will continue the conversation there.

Thanks a lot

Álvaro
