### ISSUE TITLE
Exception thrown running latest version of Airflow container

### ISSUE THREAD

**Issue by dixonl90** [bitnami/bitnami-docker-airflow#52]
**Description**

Running the latest version of the container leads to an exception being thrown after authentication to the web UI

**Steps to reproduce the issue:**

1. $ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-airflow/master/docker-compose.yml
2. $ docker-compose up
3. Navigate to http://127.0.0.1:8080
4. Login with the default username and password

**Describe the results you received:**

An exception is thrown:

```
-------------------------------------------------------------------------------
Node: e845ce785ef2
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/www_rbac/views.py", line 329, in index
    tags=tags)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/www_rbac/views.py", line 183, in render_template
    **kwargs
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask_appbuilder/baseviews.py", line 281, in render_template
    template, **dict(list(kwargs.items()) + list(self.extra_args.items()))
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/www_rbac/templates/airflow/dags.html", line 19, in top-level template code
    {% extends base_template %}
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/www_rbac/templates/airflow/master.html", line 19, in top-level template code
    {% extends 'appbuilder/baselayout.html' %}
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 19, in block "body"
    {% block content %}
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/www_rbac/templates/airflow/dags.html", line 95, in block "content"
    <a href="{{ url_for('Airflow.'+ dag.get_default_view(), dag_id=dag.dag_id) }}" title="{{ dag.description[0:80] + '...' if dag.description|length > 80 else dag.description }}">
TypeError: object of type 'NoneType' has no len()
```

**Describe the results you expected:**

To see the Airflow homepage

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:    
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 7
  Paused: 0
  Stopped: 1
 Images: 132
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-7634-generic
 Operating System: Pop!_OS 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.65GiB
 Name: pop-os
 ID: XF76:2XL3:P74Q:BC2K:2BMU:UAS5:MJR3:NDPZ:FDOH:O447:PK35:Z6BK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

I was able to reproduce the issue. We will work on publishing a fixed revision, I will update this ticket as soon as it is available. Thanks for reporting.

**Comment by andresbono** [comment]
Hi @dixonl90, it seems this issue has been triggered by an incompatibility between the version of airflow webserver, scheduler and worker. Some containers are now using version `1.10.11` while the webserver is still using `1.10.10`. Could you please stick to `1.10.10` for all the components until we release the latest version of the webserver? You can do this by changing the container images tags:

```diff
@@ -17,7 +17,7 @@ services:
     environment:
       - ALLOW_EMPTY_PASSWORD=yes
   airflow-scheduler:
-    image: docker.io/bitnami/airflow-scheduler:1-debian-10
+    image: docker.io/bitnami/airflow-scheduler:1.10.10
     environment:
       - AIRFLOW_DATABASE_NAME=bitnami_airflow
       - AIRFLOW_DATABASE_USERNAME=bn_airflow
@@ -26,7 +26,7 @@ services:
     volumes:
       - airflow_scheduler_data:/bitnami
   airflow-worker:
-    image: docker.io/bitnami/airflow-worker:1-debian-10
+    image: docker.io/bitnami/airflow-worker:1.10.10
     environment:
       - AIRFLOW_DATABASE_NAME=bitnami_airflow
       - AIRFLOW_DATABASE_USERNAME=bn_airflow
@@ -35,7 +35,7 @@ services:
     volumes:
       - airflow_worker_data:/bitnami
   airflow:
-    image: docker.io/bitnami/airflow:1-debian-10
+    image: docker.io/bitnami/airflow:1.10.10
     environment:
       - AIRFLOW_DATABASE_NAME=bitnami_airflow
       - AIRFLOW_DATABASE_USERNAME=bn_airflow
```

**Comment by andresbono** [comment]
Hi @dixonl90, bitnami/airflow `1.10.11-debian-10-r0` was released https://github.com/bitnami/bitnami-docker-airflow/commit/b085539e551fdf1283f81721c77add9aa18c46f8. The version of all the components are now in sync.
