### ISSUE TITLE
Container fails when "ldap.tls.enabled = false" as env variable AIRFLOW_LDAP_USE_TLS has no default value set

### ISSUE THREAD

**Issue by iptizer** [bitnami/bitnami-docker-airflow#54]
**Description**

When setting *ldap.tls.enabled = false* in the corresponsing helm chart the airflow-web container fails.

**Steps to reproduce the issue:**

Use the bitnami helm chart with the following values:

```sh
ingress:
  enabled: true
  hosts:
    - name: airflow.mydomain.de

postgresql:
  postgresqlUsername: bn_airflow
  postgresqlPassword: 1223pass

# setting of ldaps tring not possible
ldap:
  enabled: true
  uri: ldap://myldap.com:3838
  base: "memberof=group"
  bind_dn: "CN=user"
  bind_pw: "123pass"
  uidField: "uidField"
  tls:
    enabled: false
```

The *bitnami-web* container fails with the following exception:

```sh
nami    INFO  Initializing airflow                                                                                                  │
│ airflow INFO  ==> No injected configuration files found. Creating default config file...                                            │
│ airflow INFO  ==> Setting Airflow base URL...                                                                                       │
│ airflow INFO  ==> Enabling Webserver authentication...                                                                              │
│ airflow INFO  ==> Enabling LDAP authentication...                                                                                   │
│ airflow INFO  ==> Disabling examples...                                                                                             │
│ airflow INFO  ==> Configuring Airflow database...                                                                                   │
│ airflow INFO  ==> Setting Airflow Fernet key...                                                                                     │
│ airflow INFO  ==> Configuring Airflow Celery Executor...                                                                            │
│ airflow INFO  ==> Deploying Airflow from scratch...                                                                                 │
│ postgre INFO  Trying to connect to PostgreSQL server                                                                                │
│ postgre INFO  Found PostgreSQL server listening at airflow-postgresql:5432                                                          │
│ postgre INFO  PostgreSQL server listening and working at airflow-postgresql:5432                                                    │
│ airflow INFO  ==> Populating Airflow database...                                                                                    │
│ airflow INFO  ==> Creating Airflow user...                                                                                          │
│ Error executing 'postInstallation': Traceback (most recent call last):                                                              │
│   File "/opt/bitnami/airflow/venv/bin/airflow", line 37, in <module>                                                                │
│     args.func(args)                                                                                                                 │
│   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper                            │
│     return f(*args, **kwargs)                                                                                                       │
│   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 1438, in create_user                        │
│     appbuilder = cached_appbuilder()                                                                                                │
│   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/www_rbac/app.py", line 302, in cached_appbuilder              │
│     cached_app(config=config, testing=testing)                                                                                      │
│   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/www_rbac/app.py", line 295, in cached_app                     │
│     app, _ = create_app(config, session, testing)                                                                                   │
│   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/www_rbac/app.py", line 64, in create_app                      │
│     app.config.from_pyfile(settings.WEBSERVER_CONFIG, silent=True)                                                                  │
│   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/config.py", line 132, in from_pyfile                            │
│     exec(compile(config_file.read(), filename, "exec"), d.__dict__)                                                                 │
│   File "/opt/bitnami/airflow/webserver_config.py", line 129                                                                         │
│     AUTH_LDAP_USE_TLS=                                                                                                              │
│                      ^                                                                                                              │
│ SyntaxError: invalid syntax                                                                                                         │
│ stream closed
```

To reproduce, put the values from above in a txt file (name=airflow.yaml) and execute:

```sh
helm upgrade --install airflow bitnami/airflow -n airflow -f airflow.yaml
```

**Describe the results you received:**

Container crashed with error (se above).

**Describe the results you expected:**

The env variable in the helm chart is not set. But I'd expect this container to set the variable to **False** as described in documentation. But this is not the case.

**Additional information you deem important (e.g. issue happens only occasionally):**

As a workaround it is possible to manually add the following env variable to the *airflow-web* deployment. The pod then starts perfectly:

```sh
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-web
spec:
  template:
    spec:
      containers:
      - image: docker.io/bitnami/airflow:1.10.10-debian-10-r71
         env:
        - name: AIRFLOW_LDAP_USE_TLS
          value: "False"
```

**Version**

*Don't think this is relevant, the error is clearly not dependant on any version.*

**Comment by juan131** [comment]
Thanks so much for reporting the issue @iptizer 

I just created a PR to fix it in the chart
