### ISSUE TITLE
Papermill is not working with latest versions > 2.2.2

### ISSUE THREAD

**Issue by levihernan** [bitnami/bitnami-docker-airflow#68]
requirements.txt
```
apache-airflow[papermill]
[...]

```
Is failing when creating an output notebook.

```
*** Log file does not exist: /opt/bitnami/airflow/logs/hourly/ordersSplitHourly_WIP_V2/2021-02-05T15:07:00+00:00/16.log
*** Fetching from: http://2dc27dece507:8793/log/hourly/ordersSplitHourly_WIP_V2/2021-02-05T15:07:00+00:00/16.log

[2021-02-05 17:00:15,055] {taskinstance.py:664} INFO - Dependencies not met for <TaskInstance: hourly.ordersSplitHourly_WIP_V2 2021-02-05T15:07:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'dummy_task'}
[2021-02-05 17:00:15,057] {local_task_job.py:90} INFO - Task is not able to be run
[2021-02-05 17:00:57,122] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: hourly.ordersSplitHourly_WIP_V2 2021-02-05T15:07:00+00:00 [queued]>
[2021-02-05 17:00:57,144] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: hourly.ordersSplitHourly_WIP_V2 2021-02-05T15:07:00+00:00 [queued]>
[2021-02-05 17:00:57,144] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-02-05 17:00:57,144] {taskinstance.py:881} INFO - Starting attempt 16 of 21
[2021-02-05 17:00:57,144] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-05 17:00:57,157] {taskinstance.py:901} INFO - Executing <Task(PapermillOperator): ordersSplitHourly_WIP_V2> on 2021-02-05T15:07:00+00:00
[2021-02-05 17:00:57,160] {standard_task_runner.py:54} INFO - Started process 537 to run task
[2021-02-05 17:00:57,184] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'hourly', 'ordersSplitHourly_WIP_V2', '2021-02-05T15:07:00+00:00', '--job_id', '23930', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/hourly.py', '--cfg_path', '/tmp/tmpvb83mekt']
[2021-02-05 17:00:57,185] {standard_task_runner.py:78} INFO - Job 23930: Subtask ordersSplitHourly_WIP_V2
[2021-02-05 17:00:57,223] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: hourly.ordersSplitHourly_WIP_V2 2021-02-05T15:07:00+00:00 [running]> 2dc27dece507
[2021-02-05 17:00:57,253] {execute.py:81} INFO - Input Notebook:  /home/ubuntu/swarmcronjobs/hourly/ordersSplitHourly_WIP_V2.ipynb
[2021-02-05 17:00:57,254] {execute.py:82} INFO - Output Notebook: /home/ubuntu/tmp_aux/out-ordersSplitHourly_WIP_V2-2021-02-05T15:07:00+00:00-16.ipynb
[2021-02-05 17:00:57,334] {driver.py:195} INFO - Generating grammar tables from /opt/bitnami/airflow/venv/lib/python3.6/site-packages/blib2to3/Grammar.txt
[2021-02-05 17:00:57,374] {driver.py:198} INFO - Writing grammar tables to /.cache/black/20.8b1/Grammar3.6.12.final.0.pickle
[2021-02-05 17:00:57,374] {driver.py:202} INFO - Writing failed: [Errno 2] No such file or directory: '/.cache/black/20.8b1/tmp9pvhozjc'
[2021-02-05 17:00:57,375] {driver.py:195} INFO - Generating grammar tables from /opt/bitnami/airflow/venv/lib/python3.6/site-packages/blib2to3/PatternGrammar.txt
[2021-02-05 17:00:57,377] {driver.py:198} INFO - Writing grammar tables to /.cache/black/20.8b1/PatternGrammar3.6.12.final.0.pickle
[2021-02-05 17:00:57,377] {driver.py:202} INFO - Writing failed: [Errno 2] No such file or directory: '/.cache/black/20.8b1/tmpwyrkzml6'
[2021-02-05 17:00:57,397] {parameterize.py:101} WARNING - Input notebook does not contain a cell with tag 'parameters'
[2021-02-05 17:00:57,446] {taskinstance.py:1150} ERROR - output folder /home/ubuntu/tmp_aux doesn't exist.
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/operators/papermill_operator.py", line 58, in execute
    progress_bar=False, report_mode=True)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/papermill/execute.py", line 114, in execute_notebook
    **engine_kwargs
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/papermill/engines.py", line 341, in execute_notebook
    nb_man.notebook_start()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/papermill/engines.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/papermill/engines.py", line 198, in notebook_start
    self.save()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/papermill/engines.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/papermill/engines.py", line 139, in save
    write_ipynb(self.nb, self.output_path)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/papermill/iorw.py", line 397, in write_ipynb
    papermill_io.write(nbformat.writes(nb), path)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/papermill/iorw.py", line 128, in write
    return self.get_handler(path).write(buf, path)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/papermill/iorw.py", line 211, in write
    raise FileNotFoundError("output folder {} doesn't exist.".format(dirname))
FileNotFoundError: output folder /home/ubuntu/tmp_aux doesn't exist.
[2021-02-05 17:00:57,448] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=hourly, task_id=ordersSplitHourly_WIP_V2, execution_date=20210205T150700, start_date=20210205T170057, end_date=20210205T170057
[2021-02-05 17:01:02,107] {local_task_job.py:102} INFO - Task exited with return code 1

```

Quick fix:
```
apache-airflow[papermill]
papermill==2.2.2
[...]

```

**Comment by juan131** [comment]
Hi @levihernan 

Thanks for reporting the issue.

Could you please (step by step) what I need to do to reproduce the bug on my side? Thanks in advance.
