### ISSUE TITLE
"Column dag.last_parsed_time does not exist" error in airflow-scheduler

### ISSUE THREAD

**Issue by Narengowda** [bitnami/bitnami-docker-airflow#80]
**Description**
Airflow scheduler fails to boot with sqlalchemy error, missing column error

**Steps to reproduce the issue:**

1. Use the below mentioned docer-compose.yaml
2. docker-compose up -d
3. docker logs <container_id_of_airflow_scheduler>

docker-compose.yaml
```
version: '2'

services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:10-debian-10'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:latest
    volumes:
      - 'redis_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:latest
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      # If you'd like to load the example DAGs change this to yes!
      - AIRFLOW_LOAD_EXAMPLES=no
      # only works with 1.10.11
      #- AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE=true
      #- AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
    volumes:
      - airflow_scheduler_data:/bitnami
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./dags:/opt/bitnami/airflow/dags
      - ./db_backups:/opt/bitnami/airflow/db_backups
      - /var/run/docker.sock:/var/run/docker.sock
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:latest
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_WEBSERVER_HOST=airflow
      # only works with 1.10.11
      #- AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE=true
      #- AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
    volumes:
      - airflow_worker_data:/bitnami
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./dags:/opt/bitnami/airflow/dags
      - ./db_backups:/opt/bitnami/airflow/db_backups
      - /var/run/docker.sock:/var/run/docker.sock
  airflow:
    image: docker.io/bitnami/airflow:latest
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      # only works with 1.10.11
      #- AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE=True
      #- AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/bitnami
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./db_backups:/opt/bitnami/airflow/db_backups
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local

```

** DAG table **
```
bitnami_airflow=> \d dag
                                   Table "public.dag"
           Column            |           Type           | Collation | Nullable | Default 
-----------------------------+--------------------------+-----------+----------+---------
 dag_id                      | character varying(250)   |           | not null | 
 is_paused                   | boolean                  |           |          | 
 is_subdag                   | boolean                  |           |          | 
 is_active                   | boolean                  |           |          | 
 last_scheduler_run          | timestamp with time zone |           |          | 
 last_pickled                | timestamp with time zone |           |          | 
 last_expired                | timestamp with time zone |           |          | 
 scheduler_lock              | boolean                  |           |          | 
 pickle_id                   | integer                  |           |          | 
 fileloc                     | character varying(2000)  |           |          | 
 owners                      | character varying(2000)  |           |          | 
 description                 | text                     |           |          | 
 default_view                | character varying(25)    |           |          | 
 schedule_interval           | text                     |           |          | 
 root_dag_id                 | character varying(250)   |           |          | 
 next_dagrun                 | timestamp with time zone |           |          | 
 next_dagrun_create_after    | timestamp with time zone |           |          | 
 concurrency                 | integer                  |           | not null | 
 has_task_concurrency_limits | boolean                  |           | not null | 
Indexes:
    "dag_pkey" PRIMARY KEY, btree (dag_id)
    "idx_next_dagrun_create_after" btree (next_dagrun_create_after)
    "idx_root_dag_id" btree (root_dag_id)
Referenced by:
    TABLE "dag_tag" CONSTRAINT "dag_tag_dag_id_fkey" FOREIGN KEY (dag_id) REFERENCES dag(dag_id)
```

** Which commands I tried to fix this issue**
```
airflow db upgrade
airflow db init
airflow db reset
```

**The scheduler logs shows**
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/bitnami/python/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 367, in _run_processor_manager
    processor_manager.start()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 607, in start
    return self._run_parsing_loop()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 617, in _run_parsing_loop
    self._refresh_dag_dir()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 765, in _refresh_dag_dir
    DagModel.deactivate_deleted_dags(self._file_paths)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2215, in deactivate_deleted_dags
    dag_models = session.query(cls).all()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dag.last_parsed_time does not exist
LINE 1: ...AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_p...
                                                             ^

[SQL: SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_parsed_time AS dag_last_parsed_time, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval, dag.concurrency AS dag_concurrency, dag.has_task_concurrency_limits AS dag_has_task_concurrency_limits, dag.next_dagrun AS dag_next_dagrun, dag.next_dagrun_create_after AS dag_next_dagrun_create_after
FROM dag]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2021-04-22 03:52:29,770] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 97

```

** Airflow versions**
```
airflow version - 2.0.1
aiflow-scheduler version - 2.0.1
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 26
  Running: 22
  Paused: 0
  Stopped: 4
 Images: 25
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1040-azure
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.776GiB
 Name: stgemlwu2azmlvm1
 ID: P62A:RR4O:XDJV:MO2T:SBAN:FBRB:MDSE:B74C:FVHR:TMP4:AAS5:GEHK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

```

**Comment by juan131** [comment]
Hi @Narengowda 

It seems like you're using your custom plugins and dags, are you able to reproduce the exact issue without them? I just want to double-check that the issue is not related to that.
