### ISSUE TITLE
[bitnami/airflow-scheduler] ERROR - Exception when executing SchedulerJob._run_scheduler_loop  Traceback 

### ISSUE THREAD

**Issue by preuttip** [bitnami/bitnami-docker-airflow#82]
**Description**

**Steps to reproduce the issue:**

1. Refer instruction of https://github.com/bitnami/bitnami-docker-airflow, I'm try to construct airflow not using docker-compose so I have followed the instruction from create network, Postgreql, Redis, Airflow, Airflow-scheduler and Airflow-worker. Only Airflow-scheduler got Exited(0), the rest is running well.
2.  Here is the code of airflow-scheduler.
 docker volume create --name bn-airflow-scheduler
 docker run -d --name airflow-scheduler `
  -e AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho= `
  -e AIRFLOW_EXECUTOR=CeleryExecutor `
  -e AIRFLOW_DATABASE_NAME=bitnami_airflow `
  -e AIRFLOW_DATABASE_USERNAME=bn_airflow `
  -e AIRFLOW_DATABASE_PASSWORD=bitnami1 `
  -e AIRFLOW_LOAD_EXAMPLES=yes `
  -e AIRFLOW_WEBSERVER_HOST=airflow `
  --net airflow-tier `
  --volume bn-airflow-scheduler:/bitnami `
  bitnami/airflow-scheduler:latest

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/47513103/116384950-8bb2f080-a842-11eb-87a8-94bc532f2b26.png)

```
____________ _____________

____ |__( )_________ __/__ /________ __

____ /| |_ /__ ___/_ /_ __ /_ __ \_ | /| / /

___ ___ | / _ / _ __/ _ / / /_/ /_ |/ |/ /

_/_/ |_/_/ /_/ /_/ /_/ \____/____/|__/

[2021-04-28 09:44:07,758] {scheduler_job.py:1251} INFO - Starting the scheduler

[2021-04-28 09:44:07,758] {scheduler_job.py:1256} INFO - Processing each file at most -1 times

[2021-04-28 09:44:07,762] {dag_processing.py:252} INFO - Launched DagFileProcessorManager with pid: 65

[2021-04-28 09:44:07,764] {scheduler_job.py:1854} INFO - Resetting orphaned tasks for active dag runs

[2021-04-28 09:44:07,767] {settings.py:54} INFO - Configured default timezone Timezone('UTC')

[2021-04-28 09:44:07,783] {scheduler_job.py:1302} ERROR - Exception when executing SchedulerJob._run_scheduler_loop

Traceback (most recent call last):

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute

cursor.execute(statement, parameters)

psycopg2.errors.UndefinedColumn: column dag.last_parsed_time does not exist

LINE 1: ...AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_p...

^



The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 1284, in _execute

self._run_scheduler_loop()

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 1386, in _run_scheduler_loop

num_queued_tis = self._do_scheduling(session)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 1482, in _do_scheduling

self._create_dagruns_for_dags(guard, session)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 1585, in _create_dagruns_for_dags

for attempt in run_with_db_retries(logger=self.log):

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/tenacity/__init__.py", line 390, in __iter__

do = self.iter(retry_state=retry_state)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/tenacity/__init__.py", line 356, in iter

return fut.result()

File "/opt/bitnami/python/lib/python3.8/concurrent/futures/_base.py", line 437, in result

return self.__get_result()

File "/opt/bitnami/python/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result

raise self._exception

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 1594, in _create_dagruns_for_dags

self._create_dag_runs(query.all(), session)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all

return list(self)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__

return self._execute_and_instances(context)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances

result = conn.execute(querycontext.statement, self._params)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute

return meth(self, multiparams, params)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection

return connection._execute_clauseelement(self, multiparams, params)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement

ret = self._execute_context(

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context

self._handle_dbapi_exception(

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception

util.raise_(

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_

raise exception

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute

cursor.execute(statement, parameters)

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dag.last_parsed_time does not exist

LINE 1: ...AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_p...

^


[SQL: SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_parsed_time AS dag_last_parsed_time, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval, dag.concurrency AS dag_concurrency, dag.has_task_concurrency_limits AS dag_has_task_concurrency_limits, dag.next_dagrun AS dag_next_dagrun, dag.next_dagrun_create_after AS dag_next_dagrun_create_after



FROM dag

WHERE dag.is_paused IS false AND dag.is_active IS true AND dag.next_dagrun_create_after <= now() ORDER BY dag.next_dagrun_create_after

LIMIT %(param_1)s FOR UPDATE OF dag SKIP LOCKED]

[parameters: {'param_1': 10}]

(Background on this error at: http://sqlalche.me/e/13/f405)

Process ForkProcess-1:

Traceback (most recent call last):

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute

cursor.execute(statement, parameters)

psycopg2.errors.UndefinedColumn: column dag.last_parsed_time does not exist

LINE 1: ...AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_p...

^



The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/opt/bitnami/python/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap

self.run()

File "/opt/bitnami/python/lib/python3.8/multiprocessing/process.py", line 108, in run

self._target(*self._args, **self._kwargs)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 367, in _run_processor_manager

processor_manager.start()

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 607, in start

return self._run_parsing_loop()

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 617, in _run_parsing_loop

self._refresh_dag_dir()

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 765, in _refresh_dag_dir

DagModel.deactivate_deleted_dags(self._file_paths)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper

return func(*args, session=session, **kwargs)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2215, in deactivate_deleted_dags

dag_models = session.query(cls).all()

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all

return list(self)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__

return self._execute_and_instances(context)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances

result = conn.execute(querycontext.statement, self._params)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute

return meth(self, multiparams, params)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection

return connection._execute_clauseelement(self, multiparams, params)

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement

ret = self._execute_context(

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context

self._handle_dbapi_exception(

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception

util.raise_(

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_

raise exception

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

self.dialect.do_execute(

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute

cursor.execute(statement, parameters)

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dag.last_parsed_time does not exist

LINE 1: ...AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_p...

^


[SQL: SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_parsed_time AS dag_last_parsed_time, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval, dag.concurrency AS dag_concurrency, dag.has_task_concurrency_limits AS dag_has_task_concurrency_limits, dag.next_dagrun AS dag_next_dagrun, dag.next_dagrun_create_after AS dag_next_dagrun_create_after



FROM dag]

(Background on this error at: http://sqlalche.me/e/13/f405)

[2021-04-28 09:44:07,817] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 65

[2021-04-28 09:44:07,818] {scheduler_job.py:1305} INFO - Exited execute loop
```

**Describe the results you expected:**

Expecting running status.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: docker-desktop
 ID: QQ7O:ZC2H:JXV2:676O:7UB5:HGSI:NDFA:G3K3:MPKA:2ZXG:QX45:JZDP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Host OS : Window 10

**Comment by Mauraza** [comment]
Hi @preuttip,

could you tell us what version of airflow are you using? 
```
$ docker exec -ti airflow bash
I have no name!@c843c9125166:/$ airflow version
```

**Comment by preuttip** [comment]
Hi @Mauraza  ,

Here is it. 

PS C:\Users\2400566> docker exec -ti airflow bash
I have no name!@4fd26f0364e4:/$ airflow version
2.0.1
I have no name!@4fd26f0364e4:/$

Thanks.

**Comment by Mauraza** [comment]
Hi @preuttip,

there is a new version of airflow, could you check with this new version 2.0.2?
Thanks!

**Comment by preuttip** [comment]
Hi @Mauraza 

Can I just change the last line from "latest" to "2.0.2"?

$ docker run -d --name airflow -p 8080:8080 \
 -e AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho= \
 -e AIRFLOW_EXECUTOR=CeleryExecutor \
 -e AIRFLOW_DATABASE_NAME=bitnami_airflow \
 -e AIRFLOW_DATABASE_USERNAME=bn_airflow \
 -e AIRFLOW_DATABASE_PASSWORD=bitnami1 \
 -e AIRFLOW_LOAD_EXAMPLES=yes \
 -e AIRFLOW_PASSWORD=bitnami123 \
 -e AIRFLOW_USERNAME=user \
 -e AIRFLOW_EMAIL=user@example.com \
 --net airflow-tier \
 --volume airflow_data:/bitnami \
 bitnami/airflow:latest

**Comment by preuttip** [comment]
Hi @Mauraza ,

Thanks for your advice. It's seem to be working well after change tag version from "latest" to "2.0.2"

![image](https://user-images.githubusercontent.com/47513103/117092588-e9869180-ad88-11eb-8abc-2f47777ca8c6.png)

![image](https://user-images.githubusercontent.com/47513103/117092614-fefbbb80-ad88-11eb-9c2d-3b78153d16d8.png)
